export const ROUTE_PATHS = {
  DEFAULT: "",
  LOGIN: "login",
  REGISTER: "register",
  PERMISSION_DENIED: "permission-denied",
  ORDER: "order",
  USER: "user",
  BLOG: "blog",
  BANNER: "banner",
  CATEGORY: "category",
  ADD_CATEGORY: "category/add",
  EDIT_CATEGORY_BASE: "category/edit",
  EDIT_CATEGORY: "category/edit/:id",
  PRODUCT: "product",
  ADD_PRODUCT: "product/add",
  EDIT_PRODUCT_BASE: "product/edit",
  EDIT_PRODUCT: "product/edit/:id",
  VOUCHER: "voucher",
  ADD_VOUCHER: "voucher/add",
  EDIT_VOUCHER_BASE: "voucher/edit",
  EDIT_VOUCHER: "voucher/edit/:id",
  ADD_BLOG: "blog/add",
  EDIT_BLOG_BASE: "blog/edit",
  EDIT_BLOG: "blog/edit/:id",
  EDIT_ORDER_BASE: "order/edit",
  EDIT_ORDER: "order/edit/:id",
  LOGOUT: "logout",
};
