version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "xhoangdev"
      MYSQL_USER: "xhoang"
      MYSQL_PASSWORD: "xhoangdev"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "ktx"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - local_dev
volumes:
  mysql-data:
    driver: local
networks:
  local_dev:
    driver: bridge
