const RolePaths: { [key: string]: string[] } = {
  admin: [
    "/",
    "/product",
    "/device",
    "/device/edit/:id",
    "/user",
    "/user/add",
    "/user/edit/:id",
    "/user/view/:id",
    "/banner",
    "/category",
    "/category/add",
    "/category/edit/:id",
    "/product",
    "/product/add",
    "/product/edit/:id",
    "/room",
    "/room/add",
    "/room/edit/:id",
    "/voucher",
    "/voucher/add",
    "/voucher/edit/:id",
    "/blog",
    "/blog/add",
    "/blog/edit/:id",
    "/logout",
    "/request",
    "/request/edit/:id",
    "/request/detail/:id",
  ],
  manager: [],
  guest: ["/login", "/register"],
  onlyGuest: ["/login", "/register"],
};

export default RolePaths;
